### ISSUE TITLE
What is the status of this repo?

### ISSUE THREAD

**Issue by fabianmoronzirfas** [technologiestiftung/citylab-slides#9]
I this still in use or can this be archived?

**Comment by tori-d** [comment]
Not currently actively in use but I see it as still valuable?

It's convenient to be able to have slides hosted online. Makes it easy to share the slides via social media, for example. But I can't say when I would next use this tool...

**Comment by fabianmoronzirfas** [comment]
Okay. Cool. Just wanted to know. We added a CODEOWNERS file to this repo. So it is in your reponsability. :)
